In [1]:
import dotenv
dotenv.load_dotenv('../../.env')

from dx_client import DXClient, DXClientConfig
from dx_client.cache import DuckDBCache

In [2]:
cacheInstance = DuckDBCache()
config = DXClientConfig(
    
)
client =DXClient(config=config, cache=cacheInstance)

client.connect()

In [3]:
dd = client.get_data_dictionary(refresh=False)

In [4]:
# 1. search hypertension related fields


# 在 title、folder_path、description 中搜索
htn = dd[
    dd['title'].str.lower().str.contains('hypertension|blood pressure|systolic|diastolic', na=False) |
    dd['folder_path'].str.lower().str.contains('hypertension|blood.pressure', na=False)
]

htn
# htn[['entity', 'name', 'title', 'type', 'folder_path', 'coding_name']].to_string()

,entity,name,type,primary_key_type,title,description,coding_name,concept,folder_path,is_multi_select,is_sparse_coding,linkout,longitudinal_axis_type,referenced_entity_field,relationship,units
32,participant,p36_i0,string,,Blood pressure device ID | Instance 0,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
33,participant,p36_i1,string,,Blood pressure device ID | Instance 1,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
34,participant,p36_i2,string,,Blood pressure device ID | Instance 2,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
35,participant,p36_i3,string,,Blood pressure device ID | Instance 3,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
36,participant,p37_i0,string,,Blood pressure manual sphygmomanometer device ...,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32221,participant,p132187,integer,,Source of report of O13 (gestational [pregnanc...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32222,participant,p132188,date,,Date O14 first reported (gestational [pregnanc...,None,data_coding_819,None,Health-related outcomes/First occurrences/Preg...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32223,participant,p132189,integer,,Source of report of O14 (gestational [pregnanc...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32226,participant,p132192,date,,Date O16 first reported (unspecified maternal ...,None,data_coding_819,None,Health-related outcomes/First occurrences/Preg...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32227,participant,p132193,integer,,Source of report of O16 (unspecified maternal ...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN

In [5]:
# 2. 查看 ICD-10 诊断相关 entity

available_entities = dd['entity'].unique()
print(available_entities)

<StringArray>
[            'participant',  'covid19_result_england',
 'covid19_result_scotland',    'covid19_result_wales',
             'gp_clinical',              'gp_scripts',
        'gp_registrations',                   'hesin',
              'hesin_diag',              'hesin_oper',
          'hesin_critical',         'hesin_maternity',
          'hesin_delivery',             'hesin_psych',
                   'death',             'death_cause',
        'olink_instance_0',        'olink_instance_2',
        'olink_instance_3']
Length: 19, dtype: str

In [6]:
# 3. 搜索协变量
covariates = dd[
    dd['title'].str.lower().str.contains('age at recruitment|sex|body mass index|bmi|assessment centre', na=False)
]

covariates

,entity,name,type,primary_key_type,title,description,coding_name,concept,folder_path,is_multi_select,is_sparse_coding,linkout,longitudinal_axis_type,referenced_entity_field,relationship,units
26,participant,p31,integer,,Sex,None,data_coding_9,None,Population characteristics/Baseline characteri...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
97,participant,p53_i0,date,,Date of attending assessment centre | Instance 0,None,,None,Assessment centre/Recruitment/Reception,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
98,participant,p53_i1,date,,Date of attending assessment centre | Instance 1,None,,None,Assessment centre/Recruitment/Reception,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
99,participant,p53_i2,date,,Date of attending assessment centre | Instance 2,None,,None,Assessment centre/Recruitment/Reception,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
100,participant,p53_i3,date,,Date of attending assessment centre | Instance 3,None,,None,Assessment centre/Recruitment/Reception,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32607,participant,p132601,integer,,Source of report of Q97 (other sex chromosome ...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Cong...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32608,participant,p132602,date,,Date Q98 first reported (other sex chromosome ...,None,data_coding_819,None,Health-related outcomes/First occurrences/Cong...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32609,participant,p132603,integer,,Source of report of Q98 (other sex chromosome ...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Cong...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32779,hesin_delivery,sexbaby,string,,Sex of baby,None,data_coding_224,None,,False,False,NaN,None,,,NaN
35241,olink_instance_0,shbg,double,,SHBG;Sex hormone-binding globulin,None,,None,,False,False,NaN,None,,,NaN

In [7]:
proteome = dd[dd['entity'].str.contains(r'olink_*')]
proteome_fields = proteome['entity'] + '.' + proteome['name']

proteome_fields

32803       olink_instance_0.eid
32804      olink_instance_0.a1bg
32805     olink_instance_0.aamdc
32806    olink_instance_0.aarsd1
32807     olink_instance_0.abca2
                  ...
38650     olink_instance_3.xrcc4
38651      olink_instance_3.yes1
38652    olink_instance_3.ythdf3
38653    olink_instance_3.zbtb16
38654    olink_instance_3.zbtb17
Length: 5852, dtype: str

In [8]:
cohort = client.create_cohort(name='auto_cohort', entity_fields=['olink_instance_0$A1BG', 'participant$p132601'], filters = {
    "logic": "and",
    "pheno_filters": {
        "logic": "and",
        "compound": [
            {
                "name": "phenotype",
                "logic": "and",
                "filters": {
                    # 字段名 → 条件列表
                    "participant$p30903_i0": [
                        {"condition": "between", "values": [0, 2]}
                    ]
                }
            }
        ]
    }
})

In [9]:
client.download_cohort(cohort_id=cohort.id)

      olink_instance_0.a1bg participant.p132601
0                   -0.0936                None
1                    0.0699                None
2                   -0.2004                None
3                   -0.0693                None
4                       NaN                None
...                     ...                 ...
6224                    NaN                None
6225                    NaN                None
6226                -0.0002                None
6227                 0.4116                None
6228                -0.1915                None

[6229 rows x 2 columns]

In [10]:
client.list_cohorts(refresh=True)

[DXRecordInfo(id='record-J7FZ0kQJj70Q86Fj8qbzbvVX', name='auto_cohort', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', created=1775714406000, modified=1775714406131, state='open', description='', properties={}, types=['DatabaseQuery', 'CohortBrowser'], details={}, class='record', sponsored=False, hidden=False, links=['record-J77PBFjJVpqqvFz65XvV0Kk6'], tags=[], createdBy={'user': 'user-jiehua_li'}, size=847),
 DXRecordInfo(id='record-J7FZ070Jj70j2y1f82K5XVqF', name='auto_cohort', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', created=1775714332000, modified=1775714332790, state='open', description='', properties={}, types=['DatabaseQuery', 'CohortBrowser'], details={}, class='record', sponsored=False, hidden=False, links=['record-J77PBFjJVpqqvFz65XvV0Kk6'], tags=[], createdBy={'user': 'user-jiehua_li'}, size=847),
 DXRecordInfo(id='record-J7FYz6QJj70v47f16jXvKXY2', name='auto_cohort', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', created=1775714202000, modified=1775714202362, state='open', description='', properties={}, types=['DatabaseQuery', 'CohortBrowser'], details={}, class='record', sponsored=False, hidden=False, links=['record-J77PBFjJVpqqvFz65XvV0Kk6'], tags=[], createdBy={'user': 'user-jiehua_li'}, size=847),
 DXRecordInfo(id='record-J7FYp30Jj70YvV1xK7X3JQZY', name='olink_cohort', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', created=1775713548000, modified=1775713548320, state='open', description='', properties={}, types=['DatabaseQuery', 'CohortBrowser'], details={}, class='record', sponsored=False, hidden=False, links=['record-J77PBFjJVpqqvFz65XvV0Kk6'], tags=[], createdBy={'user': 'user-jiehua_li'}, size=146836),
 DXRecordInfo(id='record-J7F9G7jJj70V13Ygkyb14qjg', name='auto_cohort', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', created=1775670815000, modified=1775670815822, state='closed', description='', properties={}, types=['DatabaseQuery', 'CohortBrowser'], details={}, class='record', sponsored=False, hidden=False, links=['record-J77PBFjJVpqqvFz65XvV0Kk6'], tags=[], createdBy={'user': 'user-jiehua_li'}, size=464),
 DXRecordInfo(id='record-J79ZXvQJj70j64qqy14Ypxgy', name='pwas_replicate', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', created=1775454578000, modified=1775454578556, state='closed', description='', properties={}, types=['DatabaseQuery', 'CohortBrowser'], details={}, class='record', sponsored=False, hidden=False, links=['record-J77PBFjJVpqqvFz65XvV0Kk6', 'database-J77JYVjJVpqqx189JkJb87qG', 'database-Fx7Fj58JjG8Yf6bKPX9Yzykf'], tags=[], createdBy={'user': 'user-jiehua_li'}, size=4503)]

In [11]:
client.get_cohort("record-J79ZXvQJj70j64qqy14Ypxgy",refresh=True)

DXRecordInfo(id='record-J79ZXvQJj70j64qqy14Ypxgy', name='pwas_replicate', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', created=1775454578000, modified=1775454578556, state='closed', description='', properties={}, types=['DatabaseQuery', 'CohortBrowser'], details={'dashboardConfig': {'cohort_browser': {'config': {'showHeader': True, 'showFooter': True, 'showFilter': True}, 'id': 'cohort_browser', 'type': 'cohort_browser', 'containers': [{'id': 'dashboard_tiles', 'title': 'Overview', 'tiles': [], 'type': 'FieldsAsTiles', 'options': {}}, {'id': 'ted_container', 'title': 'Data Preview', 'tiles': [{'id': 'ted@participant', 'title': 'Participant', 'type': 'Table', 'dataQuery': {'fields': {'participant$eid': 'participant$eid', 'participant$p30903_i0': 'participant$p30903_i0'}, 'entity': 'participant'}, 'options': {'columns': [{'id': 'participant$eid', 'title': 'Participant ID', 'isPinned': True, 'isPrimary': True}, {'id': 'participant$p30903_i0', 'title': 'UKB-PPP Consortium selected participant | Instance 0', 'type': 'integer_categorical_sparse', 'isPrimary': False}]}, 'layout': {'height': 1, 'width': 1}}, {'type': 'Table', 'id': 'ted@olink_instance_0', 'title': 'Olink Instance 0 NPX Result', 'dataQuery': {'fields': {'olink_instance_0$eid': 'olink_instance_0$eid', 'participant$eid': 'participant$eid', 'olink_instance_0$a1bg': 'olink_instance_0$a1bg', 'olink_instance_0$aamdc': 'olink_instance_0$aamdc'}, 'entity': 'olink_instance_0'}, 'options': {'columns': [{'id': 'olink_instance_0$eid', 'title': 'Participant ID', 'type': 'string', 'isPinned': True, 'isLocked': True, 'isPrimary': True}, {'id': 'participant$eid', 'title': 'Participant ID', 'type': 'string', 'isPinned': False, 'isLocked': True, 'isPrimary': True}, {'id': 'olink_instance_0$a1bg', 'title': 'A1BG;Alpha-1B-glycoprotein', 'type': 'double', 'isPrimary': False}, {'id': 'olink_instance_0$aamdc', 'title': 'AAMDC;Mth938 domain-containing protein', 'type': 'double', 'isPrimary': False}]}, 'layout': {'height': 1, 'width': 1}}], 'type': 'TedContainer', 'options': {}}, {'id': 'variant_browser_container', 'title': 'Germline Variants', 'tiles': [{'id': 'variant_browser_plots_lollipop', 'title': 'Variant Browser Lollipop Plot', 'type': 'Lollipop', 'dataQuery': {'computeAlleleFrequency': 'genotype$type', 'fields': {'allele_frequency': 'allele$gnomad201_alt_freq', 'allele_type': 'allele$allele_type', 'alt': 'allele$alt', 'alt_count': 'allele$alt_count', 'chr': 'allele$chr', 'consequence': 'allele$worst_effect', 'id': 'allele$a_id', 'locus': 'allele$locus_id', 'pos': 'allele$pos', 'ref': 'allele$ref', 'rsid': 'allele$dbsnp151_rsid', 'y': 'allele$alt_freq'}, 'isCohort': True, 'limit': 10000}, 'options': {}, 'layout': {'height': 1, 'width': 1}}, {'id': 'variant_browser_plots_transcript', 'title': 'Variant Browser Transcript Plot', 'type': 'Transcript', 'dataQuery': {'fields': {'id': 'transcript$transcript_name', 'gene': 'transcript$gene_name', 'chr': 'transcript$chr', 'pos': 'transcript$pos', 'pos_end': 'transcript$end_pos', 'exons': 'transcript$exon', 'strand': 'transcript$strand'}, 'isCohort': False, 'limit': 10000}, 'options': {}, 'layout': {'height': 1, 'width': 1}}, {'id': 'variant_browser_table', 'dataID': 'variant_browser_plots_lollipop', 'title': 'Variant Browser Table', 'type': 'Table', 'dataQuery': {'fields': {}}, 'options': {'columns': [{'id': 'id', 'title': 'Location', 'isStatic': True}, {'id': 'rsid', 'title': 'RSID'}, {'id': 'ref', 'title': 'Reference'}, {'id': 'alt', 'title': 'Alternate'}, {'id': 'alleleType', 'title': 'Type'}, {'id': 'consequence', 'title': 'Consequence (Most severe by gene)'}, {'id': 'cohortAlleleFrequency', 'title': 'Cohort AF'}, {'id': 'y', 'title': 'Population AF'}, {'id': 'alleleFrequency', 'title': 'GnomAD AF'}]}, 'layout': {'height': 1, 'width': 1}}], 'type': 'GenomeBrowser', 'options': {'genomicRangeSearch': {'chr': '1', 'end': 55065852, 'start': 55038548, 'name': 'PCSK9'}}}]}, 'locus_detail': {'config': None, 'containers': [], 'type': 'locus_detail', 'id': 'locus_detail'}}, 'databases': [{'app917657_20260402210224': {'$dnanexus_link': 'database-J77JYVjJVpqqx189JkJb87qG'}}, {'grch38_92_euw2_transcript': {'$dnanexus_link': 'database-Fx7Fj58JjG8Yf6bKPX9Yzykf'}}], 'dataset': {'$dnanexus_link': 'record-J77PBFjJVpqqvFz65XvV0Kk6'}, 'description': '', 'name': 'pwas_replicate', 'filters': {'pheno_filters': {'compound': [{'name': 'phenotype', 'logic': 'and', 'filters': {'participant$p30903_i0': [{'condition': 'between', 'values': [0, 2]}]}, 'entity': {'logic': 'and', 'name': 'participant', 'operator': 'exists', 'children': []}}], 'logic': 'and'}, 'assay_filters': {'compound': [], 'logic': 'and'}, 'logic': 'and'}, 'schema': 'ds-ukbrap-ver20', 'sql': 'SELECT `participant_0001_1`.`eid` AS `eid` FROM `database_j77jyvjjvpqqx189jkjb87qg__app917657_20260402210224`.`participant_0001` AS `participant_0001_1` LEFT OUTER JOIN `database_j77jyvjjvpqqx189jkjb87qg__app917657_20260402210224`.`participant_0118` AS `participant_0118_1` ON `participant_0001_1`.`eid` = `participant_0118_1`.`eid` WHERE `participant_0118_1`.`p30903_i0` BETWEEN 0 AND 2', 'version': '3.0'}, class='record', sponsored=False, hidden=False, links=['record-J77PBFjJVpqqvFz65XvV0Kk6', 'database-J77JYVjJVpqqx189JkJb87qG', 'database-Fx7Fj58JjG8Yf6bKPX9Yzykf'], tags=[], createdBy={'user': 'user-jiehua_li'}, size=4503)

In [12]:
dd[dd['entity'].str.contains('olink')]

,entity,name,type,primary_key_type,title,description,coding_name,concept,folder_path,is_multi_select,is_sparse_coding,linkout,longitudinal_axis_type,referenced_entity_field,relationship,units
32803,olink_instance_0,eid,string,primary_key,Participant ID,None,,None,,False,False,NaN,None,,,NaN
32804,olink_instance_0,a1bg,double,,A1BG;Alpha-1B-glycoprotein,None,,None,,False,False,NaN,None,,,NaN
32805,olink_instance_0,aamdc,double,,AAMDC;Mth938 domain-containing protein,None,,None,,False,False,NaN,None,,,NaN
32806,olink_instance_0,aarsd1,double,,AARSD1;Alanyl-tRNA editing protein Aarsd1,None,,None,,False,False,NaN,None,,,NaN
32807,olink_instance_0,abca2,double,,ABCA2;ATP-binding cassette sub-family A member 2,None,,None,,False,False,NaN,None,,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38650,olink_instance_3,xrcc4,double,,XRCC4;DNA repair protein XRCC4,None,,None,,False,False,NaN,None,,,NaN
38651,olink_instance_3,yes1,double,,YES1;Tyrosine-protein kinase Yes,None,,None,,False,False,NaN,None,,,NaN
38652,olink_instance_3,ythdf3,double,,YTHDF3;YTH domain-containing family protein 3,None,,None,,False,False,NaN,None,,,NaN
38653,olink_instance_3,zbtb16,double,,ZBTB16;Zinc finger and BTB domain-containing p...,None,,None,,False,False,NaN,None,,,NaN
38654,olink_instance_3,zbtb17,double,,ZBTB17;Zinc finger and BTB domain-containing p...,None,,None,,False,False,NaN,None,,,NaN

In [ ]:
# 下载完整的olink数据
olink_cohort_set = dd[dd['entity'].str.contains(r'olink_*')]
olink_fields = olink_cohort_set['entity'] + '$' + olink_cohort_set['name']

olink_cohort = client.create_cohort(
    name='olink_cohort', 
    entity_fields=olink_fields.to_list(), 
    filters={}
    )

In [ ]:
olink_df = client.download_cohort(olink_cohort.id)

In [17]:
client.get_cohort(olink_cohort.id)

DXRecordInfo(id='record-J7FZ3v0Jj70kyKX7KKYFx6v8', name='olink_cohort', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', created=1775714800000, modified=1775714800321, state='open', description='', properties={}, types=['DatabaseQuery', 'CohortBrowser'], details={'databases': ['database-J77JYVjJVpqqx189JkJb87qG', 'database-Fx7Fj58JjG8Yf6bKPX9Yzykf'], 'dataset': {'$dnanexus_link': 'record-J77PBFjJVpqqvFz65XvV0Kk6'}, 'description': '', 'filters': {}, 'schema': 'ds-ukbrap-ver20', 'sql': 'SELECT `participant_0001_1`.`eid` AS `eid` FROM `database_j77jyvjjvpqqx189jkjb87qg__app917657_20260402210224`.`participant_0001` AS `participant_0001_1`;', 'version': '3.0', 'fields': ['olink_instance_0$eid', 'olink_instance_0$a1bg', 'olink_instance_0$aamdc', 'olink_instance_0$aarsd1', 'olink_instance_0$abca2', 'olink_instance_0$abhd14b', 'olink_instance_0$abl1', 'olink_instance_0$abo', 'olink_instance_0$abraxas2', 'olink_instance_0$acaa1', 'olink_instance_0$acadm', 'olink_instance_0$acadsb', 'olink_instance_0$acan', 'olink_instance_0$ace', 'olink_instance_0$ace2', 'olink_instance_0$ache', 'olink_instance_0$acot13', 'olink_instance_0$acox1', 'olink_instance_0$acp1', 'olink_instance_0$acp5', 'olink_instance_0$acp6', 'olink_instance_0$acrbp', 'olink_instance_0$acrv1', 'olink_instance_0$acsl1', 'olink_instance_0$acta2', 'olink_instance_0$actn2', 'olink_instance_0$actn4', 'olink_instance_0$acvrl1', 'olink_instance_0$acy1', 'olink_instance_0$acy3', 'olink_instance_0$acyp1', 'olink_instance_0$ada', 'olink_instance_0$ada2', 'olink_instance_0$adam12', 'olink_instance_0$adam15', 'olink_instance_0$adam22', 'olink_instance_0$adam23', 'olink_instance_0$adam8', 'olink_instance_0$adam9', 'olink_instance_0$adamts1', 'olink_instance_0$adamts13', 'olink_instance_0$adamts15', 'olink_instance_0$adamts16', 'olink_instance_0$adamts4', 'olink_instance_0$adamts8', 'olink_instance_0$adamtsl2', 'olink_instance_0$adamtsl4', 'olink_instance_0$adamtsl5', 'olink_instance_0$adcyap1r1', 'olink_instance_0$add1', 'olink_instance_0$adgrb3', 'olink_instance_0$adgrd1', 'olink_instance_0$adgre1', 'olink_instance_0$adgre2', 'olink_instance_0$adgre5', 'olink_instance_0$adgrf5', 'olink_instance_0$adgrg1', 'olink_instance_0$adgrg2', 'olink_instance_0$adgrv1', 'olink_instance_0$adh1b', 'olink_instance_0$adh4', 'olink_instance_0$adipoq', 'olink_instance_0$adm', 'olink_instance_0$adra2a', 'olink_instance_0$afap1', 'olink_instance_0$afm', 'olink_instance_0$afp', 'olink_instance_0$agbl2', 'olink_instance_0$ager', 'olink_instance_0$agr2', 'olink_instance_0$agr3', 'olink_instance_0$agrn', 'olink_instance_0$agrp', 'olink_instance_0$agt', 'olink_instance_0$agxt', 'olink_instance_0$ahcy', 'olink_instance_0$ahnak', 'olink_instance_0$ahnak2', 'olink_instance_0$ahsa1', 'olink_instance_0$ahsg', 'olink_instance_0$ahsp', 'olink_instance_0$aida', 'olink_instance_0$aif1', 'olink_instance_0$aif1l', 'olink_instance_0$aifm1', 'olink_instance_0$ak1', 'olink_instance_0$ak2', 'olink_instance_0$akap12', 'olink_instance_0$akr1b1', 'olink_instance_0$akr1b10', 'olink_instance_0$akr1c4', 'olink_instance_0$akr7l', 'olink_instance_0$akt1s1', 'olink_instance_0$akt2', 'olink_instance_0$akt3', 'olink_instance_0$alcam', 'olink_instance_0$aldh1a1', 'olink_instance_0$aldh2', 'olink_instance_0$aldh3a1', 'olink_instance_0$aldh5a1', 'olink_instance_0$alms1', 'olink_instance_0$alpi', 'olink_instance_0$alpp', 'olink_instance_0$ambn', 'olink_instance_0$ambp', 'olink_instance_0$amdhd2', 'olink_instance_0$amfr', 'olink_instance_0$amigo1', 'olink_instance_0$amigo2', 'olink_instance_0$amn', 'olink_instance_0$amot', 'olink_instance_0$amotl2', 'olink_instance_0$ampd3', 'olink_instance_0$amy1a_amy1b_amy1c', 'olink_instance_0$amy2a', 'olink_instance_0$amy2b', 'olink_instance_0$ang', 'olink_instance_0$angpt1', 'olink_instance_0$angpt2', 'olink_instance_0$angptl1', 'olink_instance_0$angptl2', 'olink_instance_0$angptl3', 'olink_instance_0$angptl4', 'olink_instance_0$angptl7', 'olink_instance_0$ank2', 'olink_instance_0$ankmy2', 'olink_instance_0$ankra2', 'olink_instance_0$ankrd54', 'olink_instance_0$anp32c', 'olink_instance_0$anpep', 'olink_instance_0$anxa1', 'olink_instance_0$anxa10', 'olink_instance_0$anxa11', 'olink_instance_0$anxa2', 'olink_instance_0$anxa3', 'olink_instance_0$anxa4', 'olink_instance_0$anxa5', 'olink_instance_0$aoc1', 'olink_instance_0$aoc3', 'olink_instance_0$ap1g2', 'olink_instance_0$ap2b1', 'olink_instance_0$ap3b1', 'olink_instance_0$ap3s2', 'olink_instance_0$apbb1ip', 'olink_instance_0$apcs', 'olink_instance_0$apex1', 'olink_instance_0$aplp1', 'olink_instance_0$apoa1', 'olink_instance_0$apoa2', 'olink_instance_0$apoa4', 'olink_instance_0$apob', 'olink_instance_0$apobr', 'olink_instance_0$apoc1', 'olink_instance_0$apod', 'olink_instance_0$apoe', 'olink_instance_0$apof', 'olink_instance_0$apoh', 'olink_instance_0$apol1', 'olink_instance_0$apom', 'olink_instance_0$app', 'olink_instance_0$appl2', 'olink_instance_0$aprt', 'olink_instance_0$araf', 'olink_instance_0$areg', 'olink_instance_0$arf6', 'olink_instance_0$arfip1', 'olink_instance_0$arg1', 'olink_instance_0$arg2', 'olink_instance_0$arhgap1', 'olink_instance_0$arhgap25', 'olink_instance_0$arhgap30', 'olink_instance_0$arhgap45', 'olink_instance_0$arhgap5', 'olink_instance_0$arhgef1', 'olink_instance_0$arhgef10', 'olink_instance_0$arhgef12', 'olink_instance_0$arhgef5', 'olink_instance_0$arid3a', 'olink_instance_0$arid4b', 'olink_instance_0$arl13b', 'olink_instance_0$arl2bp', 'olink_instance_0$armcx2', 'olink_instance_0$arnt', 'olink_instance_0$arntl', 'olink_instance_0$arsa', 'olink_instance_0$arsb', 'olink_instance_0$art3', 'olink_instance_0$art5', 'olink_instance_0$artn', 'olink_instance_0$asah1', 'olink_instance_0$asah2', 'olink_instance_0$asgr1', 'olink_instance_0$asgr2', 'olink_instance_0$aspn', 'olink_instance_0$aspscr1', 'olink_instance_0$asrgl1', 'olink_instance_0$ass1', 'olink_instance_0$atf2', 'olink_instance_0$atf4', 'olink_instance_0$atg16l1', 'olink_instance_0$atg4a', 'olink_instance_0$atox1', 'olink_instance_0$atp1b1', 'olink_instance_0$atp1b2', 'olink_instance_0$atp1b3', 'olink_instance_0$atp1b4', 'olink_instance_0$atp2b4', 'olink_instance_0$atp5f1d', 'olink_instance_0$atp5if1', 'olink_instance_0$atp5po', 'olink_instance_0$atp6ap2', 'olink_instance_0$atp6v1d', 'olink_instance_0$atp6v1f', 'olink_instance_0$atp6v1g1', 'olink_instance_0$atp6v1g2', 'olink_instance_0$atraid', 'olink_instance_0$atrn', 'olink_instance_0$atxn10', 'olink_instance_0$atxn2', 'olink_instance_0$atxn2l', 'olink_instance_0$atxn3', 'olink_instance_0$axin1', 'olink_instance_0$axl', 'olink_instance_0$azi2', 'olink_instance_0$azu1', 'olink_instance_0$b2m', 'olink_instance_0$b3gat3', 'olink_instance_0$b3gnt7', 'olink_instance_0$b4galt1', 'olink_instance_0$b4gat1', 'olink_instance_0$babam1', 'olink_instance_0$bach1', 'olink_instance_0$bag3', 'olink_instance_0$bag4', 'olink_instance_0$bag6', 'olink_instance_0$baiap2', 'olink_instance_0$bambi', 'olink_instance_0$bank1', 'olink_instance_0$bap18', 'olink_instance_0$batf', 'olink_instance_0$bax', 'olink_instance_0$bcam', 'olink_instance_0$bcan', 'olink_instance_0$bcat1', 'olink_instance_0$bcat2', 'olink_instance_0$bche', 'olink_instance_0$bcl2', 'olink_instance_0$bcl2l1', 'olink_instance_0$bcl2l11', 'olink_instance_0$bcl2l15', 'olink_instance_0$bcl7a', 'olink_instance_0$bcl7b', 'olink_instance_0$bcr', 'olink_instance_0$bdnf', 'olink_instance_0$becn1', 'olink_instance_0$bex3', 'olink_instance_0$bglap', 'olink_instance_0$bgn', 'olink_instance_0$bhlhe40', 'olink_instance_0$bhmt2', 'olink_instance_0$bid', 'olink_instance_0$bin2', 'olink_instance_0$birc2', 'olink_instance_0$blmh', 'olink_instance_0$blnk', 'olink_instance_0$bloc1s2', 'olink_instance_0$bloc1s3', 'olink_instance_0$blvrb', 'olink_instance_0$bmp10', 'olink_instance_0$bmp4', 'olink_instance_0$bmp6', 'olink_instance_0$bmper', 'olink_instance_0$bnip2', 'olink_instance_0$bnip3l', 'olink_instance_0$boc', 'olink_instance_0$bola1', 'olink_instance_0$bola2_bola2b', 'olink_instance_0$bpifa2', 'olink_instance_0$bpifb1', 'olink_instance_0$bpifb2', 'olink_instance_0$brap', 'olink_instance_0$brd1', 'olink_instance_0$brd2', 'olink_instance_0$brd3', 'olink_instance_0$brdt', 'olink_instance_0$brk1', 'olink_instance_0$brme1', 'olink_instance_0$brsk2', 'olink_instance_0$bsg', 'olink_instance_0$bsnd', 'olink_instance_0$bst1', 'olink_instance_0$bst2', 'olink_instance_0$btc', 'olink_instance_0$btd', 'olink_instance_0$btla', 'olink_instance_0$btn1a1', 'olink_instance_0$btn2a1', 'olink_instance_0$btn3a2', 'olink_instance_0$btnl10', 'olink_instance_0$c19orf12', 'olink_instance_0$c1galt1c1', 'olink_instance_0$c1qa', 'olink_instance_0$c1qbp', 'olink_instance_0$c1ql2', 'olink_instance_0$c1qtnf1', 'olink_instance_0$c1qtnf5', 'olink_instance_0$c1qtnf6', 'olink_instance_0$c1qtnf9', 'olink_instance_0$c1r', 'olink_instance_0$c1rl', 'olink_instance_0$c1s', 'olink_instance_0$c2', 'olink_instance_0$c2cd2l', 'olink_instance_0$c2orf69', 'olink_instance_0$c3', 'olink_instance_0$c4bpb', 'olink_instance_0$c5', 'olink_instance_0$c7', 'olink_instance_0$c7orf50', 'olink_instance_0$c8b', 'olink_instance_0$c9', 'olink_instance_0$c9orf40', 'olink_instance_0$ca1', 'olink_instance_0$ca11', 'olink_instance_0$ca12', 'olink_instance_0$ca13', 'olink_instance_0$ca14', 'olink_instance_0$ca2', 'olink_instance_0$ca3', 'olink_instance_0$ca4', 'olink_instance_0$ca5a', 'olink_instance_0$ca6', 'olink_instance_0$ca7', 'olink_instance_0$ca8', 'olink_instance_0$ca9', 'olink_instance_0$cabp2', 'olink_instance_0$cacna1c', 'olink_instance_0$cacna1h', 'olink_instance_0$cacnb1', 'olink_instance_0$cacnb3', 'olink_instance_0$cacybp', 'olink_instance_0$cadps', 'olink_instance_0$calb1', 'olink_instance_0$calb2', 'olink_instance_0$calca', 'olink_instance_0$calcb', 'olink_instance_0$calcoco1', 'olink_instance_0$calcoco2', 'olink_instance_0$caly', 'olink_instance_0$camkk1', 'olink_instance_0$camlg', 'olink_instance_0$camsap1', 'olink_instance_0$cant1', 'olink_instance_0$capg', 'olink_instance_0$capn3', 'olink_instance_0$caps', 'olink_instance_0$carhsp1', 'olink_instance_0$casc3', 'olink_instance_0$casp1', 'olink_instance_0$casp10', 'olink_instance_0$casp2', 'olink_instance_0$casp3', 'olink_instance_0$casp4', 'olink_instance_0$casp7', 'olink_instance_0$casp8', 'olink_instance_0$casp9', 'olink_instance_0$casq2', 'olink_instance_0$cat', 'olink_instance_0$cblif', 'olink_instance_0$cbln1', 'olink_instance_0$cbln4', 'olink_instance_0$cbs', 'olink_instance_0$cbx2', 'olink_instance_0$cc2d1a', 'olink_instance_0$ccar2', 'olink_instance_0$ccdc134', 'olink_instance_0$ccdc28a', 'olink_instance_0$ccdc50', 'olink_instance_0$ccdc80', 'olink_instance_0$ccer2', 'olink_instance_0$ccl11', 'olink_instance_0$ccl13', 'olink_instance_0$ccl14', 'olink_instance_0$ccl15', 'olink_instance_0$ccl16', 'olink_instance_0$ccl17', 'olink_instance_0$ccl18', 'olink_instance_0$ccl19', 'olink_instance_0$ccl2', 'olink_instance_0$ccl20', 'olink_instance_0$ccl21', 'olink_instance_0$ccl22', 'olink_instance_0$ccl23', 'olink_instance_0$ccl24', 'olink_instance_0$ccl25', 'olink_instance_0$ccl26', 'olink_instance_0$ccl27', 'olink_instance_0$ccl28', 'olink_instance_0$ccl3', 'olink_instance_0$ccl4', 'olink_instance_0$ccl5', 'olink_instance_0$ccl7', 'olink_instance_0$ccl8', 'olink_instance_0$ccn1', 'olink_instance_0$ccn2', 'olink_instance_0$ccn3', 'olink_instance_0$ccn4', 'olink_instance_0$ccn5', 'olink_instance_0$ccnd2', 'olink_instance_0$ccne1', 'olink_instance_0$ccs', 'olink_instance_0$cct5', 'olink_instance_0$cd101', 'olink_instance_0$cd109', 'olink_instance_0$cd14', 'olink_instance_0$cd160', 'olink_instance_0$cd163', 'olink_instance_0$cd164', 'olink_instance_0$cd164l2', 'olink_instance_0$cd177', 'olink_instance_0$cd1c', 'olink_instance_0$cd2', 'olink_instance_0$cd200', 'olink_instance_0$cd200r1', 'olink_instance_0$cd207', 'olink_instance_0$cd209', 'olink_instance_0$cd22', 'olink_instance_0$cd226', 'olink_instance_0$cd244', 'olink_instance_0$cd248', 'olink_instance_0$cd27', 'olink_instance_0$cd274', 'olink_instance_0$cd276', 'olink_instance_0$cd28', 'olink_instance_0$cd2ap', 'olink_instance_0$cd300a', 'olink_instance_0$cd300c', 'olink_instance_0$cd300e', 'olink_instance_0$cd300lf', 'olink_instance_0$cd300lg', 'olink_instance_0$cd302', 'olink_instance_0$cd33', 'olink_instance_0$cd34', 'olink_instance_0$cd36', 'olink_instance_0$cd38', 'olink_instance_0$cd3d', 'olink_instance_0$cd3e', 'olink_instance_0$cd3g', 'olink_instance_0$cd4', 'olink_instance_0$cd40', 'olink_instance_0$cd40lg', 'olink_instance_0$cd46', 'olink_instance_0$cd48', 'olink_instance_0$cd5', 'olink_instance_0$cd55', 'olink_instance_0$cd58', 'olink_instance_0$cd59', 'olink_instance_0$cd5l', 'olink_instance_0$cd6', 'olink_instance_0$cd63', 'olink_instance_0$cd69', 'olink_instance_0$cd7', 'olink_instance_0$cd70', 'olink_instance_0$cd72', 'olink_instance_0$cd74', 'olink_instance_0$cd79b', 'olink_instance_0$cd80', 'olink_instance_0$cd82', 'olink_instance_0$cd83', 'olink_instance_0$cd84', 'olink_instance_0$cd86', 'olink_instance_0$cd8a', 'olink_instance_0$cd93', 'olink_instance_0$cd99', 'olink_instance_0$cd99l2', 'olink_instance_0$cda', 'olink_instance_0$cdan1', 'olink_instance_0$cdc123', 'olink_instance_0$cdc25a', 'olink_instance_0$cdc26', 'olink_instance_0$cdc27', 'olink_instance_0$cdc37', 'olink_instance_0$cdc42bpb', 'olink_instance_0$cdcp1', 'olink_instance_0$cdh1', 'olink_instance_0$cdh15', 'olink_instance_0$cdh17', 'olink_instance_0$cdh2', 'olink_instance_0$cdh22', 'olink_instance_0$cdh23', 'olink_instance_0$cdh3', 'olink_instance_0$cdh4', 'olink_instance_0$cdh5', 'olink_instance_0$cdh6', 'olink_instance_0$cdhr1', 'olink_instance_0$cdhr2', 'olink_instance_0$cdhr5', 'olink_instance_0$cdk1', 'olink_instance_0$cdk5rap3', 'olink_instance_0$cdkl5', 'olink_instance_0$cdkn1a', 'olink_instance_0$cdkn2d', 'olink_instance_0$cdnf', 'olink_instance_0$cdon', 'olink_instance_0$cdsn', 'olink_instance_0$ceacam1', 'olink_instance_0$ceacam16', 'olink_instance_0$ceacam18', 'olink_instance_0$ceacam19', 'olink_instance_0$ceacam20', 'olink_instance_0$ceacam21', 'olink_instance_0$ceacam3', 'olink_instance_0$ceacam5', 'olink_instance_0$ceacam6', 'olink_instance_0$ceacam8', 'olink_instance_0$cebpa', 'olink_instance_0$cebpb', 'olink_instance_0$cela2a', 'olink_instance_0$cela3a', 'olink_instance_0$celsr2', 'olink_instance_0$cemip2', 'olink_instance_0$cend1', 'olink_instance_0$cenpf', 'olink_instance_0$cenpj', 'olink_instance_0$cep112', 'olink_instance_0$cep152', 'olink_instance_0$cep164', 'olink_instance_0$cep170', 'olink_instance_0$cep20', 'olink_instance_0$cep290', 'olink_instance_0$cep350', 'olink_instance_0$cep43', 'olink_instance_0$cep85', 'olink_instance_0$cert', 'olink_instance_0$ces1', 'olink_instance_0$ces2', 'olink_instance_0$ces3', 'olink_instance_0$cetn2', 'olink_instance_0$cetn3', 'olink_instance_0$cfb', 'olink_instance_0$cfc1', 'olink_instance_0$cfd', 'olink_instance_0$cfh', 'olink_instance_0$cfhr2', 'olink_instance_0$cfhr4', 'olink_instance_0$cfhr5', 'olink_instance_0$cfi', 'olink_instance_0$cfp', 'olink_instance_0$cga', 'olink_instance_0$cgb3_cgb5_cgb8', 'olink_instance_0$cgn', 'olink_instance_0$cgref1', 'olink_instance_0$chac2', 'olink_instance_0$chad', 'olink_instance_0$chchd10', 'olink_instance_0$chchd6', 'olink_instance_0$chek2', 'olink_instance_0$chga', 'olink_instance_0$chgb', 'olink_instance_0$chi3l1', 'olink_instance_0$chit1', 'olink_instance_0$chl1', 'olink_instance_0$chm', 'olink_instance_0$chmp1a', 'olink_instance_0$chmp6', 'olink_instance_0$chp1', 'olink_instance_0$chrdl1', 'olink_instance_0$chrdl2', 'olink_instance_0$chrm1', 'olink_instance_0$ciapin1', 'olink_instance_0$cilp', 'olink_instance_0$cinp', 'olink_instance_0$cirbp', 'olink_instance_0$cit', 'olink_instance_0$ckap4', 'olink_instance_0$ckb', 'olink_instance_0$ckmt1a_ckmt1b', 'olink_instance_0$clasp1', 'olink_instance_0$clc', 'olink_instance_0$clec10a', 'olink_instance_0$clec11a', 'olink_instance_0$clec12a', 'olink_instance_0$clec14a', 'olink_instance_0$clec1a', 'olink_instance_0$clec1b', 'olink_instance_0$clec2l', 'olink_instance_0$clec3b', 'olink_instance_0$clec4a', 'olink_instance_0$clec4c', 'olink_instance_0$clec4d', 'olink_instance_0$clec4g', 'olink_instance_0$clec4m', 'olink_instance_0$clec5a', 'olink_instance_0$clec6a', 'olink_instance_0$clec7a', 'olink_instance_0$clgn', 'olink_instance_0$clic5', 'olink_instance_0$clint1', 'olink_instance_0$clip2', 'olink_instance_0$clmp', 'olink_instance_0$clns1a', 'olink_instance_0$clpp', 'olink_instance_0$clps', 'olink_instance_0$clspn', 'olink_instance_0$clstn1', 'olink_instance_0$clstn2', 'olink_instance_0$clstn3', 'olink_instance_0$clta', 'olink_instance_0$clu', 'olink_instance_0$clul1', 'olink_instance_0$cmc1', 'olink_instance_0$cmip', 'olink_instance_0$cndp1', 'olink_instance_0$cngb3', 'olink_instance_0$cnp', 'olink_instance_0$cnpy2', 'olink_instance_0$cnpy4', 'olink_instance_0$cnst', 'olink_instance_0$cntf', 'olink_instance_0$cntn1', 'olink_instance_0$cntn2', 'olink_instance_0$cntn3', 'olink_instance_0$cntn4', 'olink_instance_0$cntn5', 'olink_instance_0$cntnap2', 'olink_instance_0$cntnap4', 'olink_instance_0$coch', 'olink_instance_0$col15a1', 'olink_instance_0$col18a1', 'olink_instance_0$col1a1', 'olink_instance_0$col24a1', 'olink_instance_0$col28a1', 'olink_instance_0$col2a1', 'olink_instance_0$col3a1', 'olink_instance_0$col4a1', 'olink_instance_0$col4a4', 'olink_instance_0$col5a1', 'olink_instance_0$col6a3', 'olink_instance_0$col9a1', 'olink_instance_0$col9a2', 'olink_instance_0$colec12', 'olink_instance_0$commd1', 'olink_instance_0$commd9', 'olink_instance_0$comp', 'olink_instance_0$comt', 'olink_instance_0$copb2', 'olink_instance_0$cope', 'olink_instance_0$coq7', 'olink_instance_0$coro1a', 'olink_instance_0$coro6', 'olink_instance_0$cox5b', 'olink_instance_0$cox6b1', 'olink_instance_0$cpa1', 'olink_instance_0$cpa2', 'olink_instance_0$cpa4', 'olink_instance_0$cpb1', 'olink_instance_0$cpb2', 'olink_instance_0$cpe', 'olink_instance_0$cplx2', 'olink_instance_0$cpm', 'olink_instance_0$cpox', 'olink_instance_0$cpped1', 'olink_instance_0$cpq', 'olink_instance_0$cptp', 'olink_instance_0$cpvl', 'olink_instance_0$cpxm1', 'olink_instance_0$cpxm2', 'olink_instance_0$cr1', 'olink_instance_0$cr2', 'olink_instance_0$cracr2a', 'olink_instance_0$cradd', 'olink_instance_0$creb3', 'olink_instance_0$crebzf', 'olink_instance_0$creg1', 'olink_instance_0$creld1', 'olink_instance_0$creld2', 'olink_instance_0$crh', 'olink_instance_0$crhbp', 'olink_instance_0$crhr1', 'olink_instance_0$crim1', 'olink_instance_0$crip2', 'olink_instance_0$crisp2', 'olink_instance_0$crisp3', 'olink_instance_0$crkl', 'olink_instance_0$crlf1', 'olink_instance_0$crnn', 'olink_instance_0$crtac1', 'olink_instance_0$crtam', 'olink_instance_0$crtap', 'olink_instance_0$crx', 'olink_instance_0$crybb1', 'olink_instance_0$crybb2', 'olink_instance_0$crygd', 'olink_instance_0$crym', 'olink_instance_0$cryzl1', 'olink_instance_0$csde1', 'olink_instance_0$csf1', 'olink_instance_0$csf1r', 'olink_instance_0$csf2', 'olink_instance_0$csf2ra', 'olink_instance_0$csf2rb', 'olink_instance_0$csf3', 'olink_instance_0$csf3r', 'olink_instance_0$csh1', 'olink_instance_0$csnk1d', 'olink_instance_0$csnk2a1', 'olink_instance_0$cspg4', 'olink_instance_0$cspg5', 'olink_instance_0$csrp3', 'olink_instance_0$cst1', 'olink_instance_0$cst3', 'olink_instance_0$cst5', 'olink_instance_0$cst6', 'olink_instance_0$cst7', 'olink_instance_0$cstb', 'olink_instance_0$ctag1a_ctag1b', 'olink_instance_0$ctbs', 'olink_instance_0$ctf1', 'olink_instance_0$cthrc1', 'olink_instance_0$ctla4', 'olink_instance_0$ctnna1', 'olink_instance_0$ctrb1', 'olink_instance_0$ctrc', 'olink_instance_0$ctrl', 'olink_instance_0$ctsb', 'olink_instance_0$ctsc', 'olink_instance_0$ctsd', 'olink_instance_0$ctse', 'olink_instance_0$ctsf', 'olink_instance_0$ctsh', 'olink_instance_0$ctsl', 'olink_instance_0$ctso', 'olink_instance_0$ctss', 'olink_instance_0$ctsv', 'olink_instance_0$ctsz', 'olink_instance_0$cuzd1', 'olink_instance_0$cwc15', 'olink_instance_0$cx3cl1', 'olink_instance_0$cxadr', 'olink_instance_0$cxcl1', 'olink_instance_0$cxcl10

In [20]:
test_cohort = client.create_cohort(
    name='test_cohort', 
    entity_fields=['olink_instance_3.txlna', 'olink_instance_3.txndc15', 'olink_instance_3.txndc5'], 
    filters={}
    )

In [21]:
client.download_cohort(test_cohort.id)

,olink_instance_3.txlna,olink_instance_3.txndc15,olink_instance_3.txndc5
0,-0.7379,0.34785,-0.7086
1,-1.0068,-0.23725,-1.1939
2,-0.0589,0.07195,0.1667
3,0.5430,0.54555,0.4492
4,0.6502,0.77285,0.4520
...,...,...,...
1118,0.5649,-0.27715,0.1879
1119,-0.8537,-0.32425,0.2975
1120,-0.2288,0.59405,-0.5741
1121,-2.0057,-0.57435,-1.5544
1122,1.2479,-0.04095,0.8910